export enum SpotlerExternalTriggerResponse {
    OK = 'OK',
    UNKNOWN = 'UNKNOWN',
    TRIGGER_NOTFOUND = 'TRIGGER_NOTFOUND',
    CONTACT_NOTFOUND = 'CONTACT_NOTFOUND',
    NOT_TRIGGERED = 'NOT_TRIGGERED'
}
