export enum SpotlerContactResponseCode {
    OK = 'OK',
    PROPERTY_INVALID = 'PROPERTY_INVALID',
    CONTACT_ALREADY_EXISTS = 'CONTACT_ALREADY_EXISTS',
    CONTACT_UNKNOWN = 'CONTACT_UNKNOWN',
    CONTACT_OPTOUT = 'CONTACT_OPTOUT',
    NO_ACTIVE_CHANNEL = 'NO_ACTIVE_CHANNEL',
    ERROR = 'ERROR'
}
